### ISSUE TITLE
Remove debug packages

### ISSUE THREAD

**Issue by wsargent** [lightbend/ssl-config#101]
The debug code in https://github.com/lightbend/ssl-config/tree/master/ssl-config-core/src/main/scala/com/typesafe/sslconfig/ssl/debug is a set of evil, evil hacks.

https://tersesystems.com/blog/2014/03/02/monkeypatching-java-classes/

It would be better to replace it with debugjsse https://github.com/tersesystems/debugjsse for 1.0.0.  If people want to enable the JSSE debug code they can do it with `-Djavax.net.debug=ssl etc`. the usual way.

**Comment by dwijnand** [comment]
Done in #138.
