### ISSUE TITLE
Drop generation of scala 2.10 artifacts

### ISSUE THREAD

**Issue by ignasi35** [lightbend/ssl-config#134]
The release matrix produces artifacts for:

- 2.13 (currently `M3` and `M4`)
- 2.12
- 2.11
- 2.10

We could drop 2.10. What are the downstream projects still relying on the 2.10 artifact?

**Comment by SethTisue** [comment]
dropping 2.10 seems fine to me, anyone still stuck on 2.10 should be fine just continuing to use whatever versions of things they're already using.

I suppose some security issue could arise necessitating a new release on 2.10 — if that happens, it could always be done by just cherry-picking the change onto a branch and releasing from there.
