### ISSUE TITLE
Restore the debug package, working on Java 11

### ISSUE THREAD

**Issue by dwijnand** [lightbend/ssl-config#142]
In https://github.com/scala/community-builds/issues/796#issuecomment-432500757 Seth indicated that ssl-config was the big blocker for the scala community build on Java 11, which was being tracked at #98.

So I opened #138 and after being able to compile on Java 11 it turned out there was some code in the `debug` subpackage that relied on privileged reflection, that is actually enforced as of Java 11.  As such ssl-config's tests didn't pass when run on Java 11.

In an attempt to keep moving I tried deleting the whole subpackage which _seemed_ to pass the community build, but it actually turned out to fail on in play-ws, because those debug API are used (they're also used in the play repo proper, and potentially in more places).

The plan is to restore the package, but backed by @wsargent's https://github.com/tersesystems/debugjsse and https://github.com/tersesystems/ocapjsse#logging.

@wsargent could you take care of this, please?

**Comment by wsargent** [comment]
@dwijnand Will do!

**Comment by dwijnand** [comment]
Thank you!

**Comment by dwijnand** [comment]
Just wanted to mention that this is still on my mind.

Master is currently unreleasable because it breaks binary compatibility.  We don't have any immediate need to release, but I don't want to risk forgetting.

If we can't resolve this using your libraries, Will, I think we might have to restore the previous classes and re-fork the repo for the Java 11 community build (cc @SethTisue).

**Comment by wsargent** [comment]
@dwijnand Added work in progress -- am working on adding tests right now for keymanager/trustmanager but you can see how logging works with wrapper.

**Comment by dwijnand** [comment]
Thanks, Will.  I pushed a commit to ensure we restore all the binary APIs.

**Comment by wsargent** [comment]
Addressed in https://github.com/lightbend/ssl-config/pull/143

**Comment by SethTisue** [comment]
can we close this out? can #143 be merged?

**Comment by dwijnand** [comment]
Fixed in #143.

**Comment by wsargent** [comment]
Should this be reopened?

**Comment by dwijnand** [comment]
For what reason?

The package was restored, and it works on Java 11: https://travis-ci.org/lightbend/ssl-config/builds/515764092
