### ISSUE TITLE
Release for 2.13.0-RC1

### ISSUE THREAD

**Issue by raboof** [lightbend/ssl-config#163]

**Comment by raboof** [comment]
Oh already done in https://github.com/lightbend/ssl-config/pull/161

**Comment by dwijnand** [comment]
and done http://repo1.maven.org/maven2/com/typesafe/ssl-config-core_2.13.0-RC1/

@raboof do you want and have bandwidth to create a GitHub release for the v0.4.0 tag, please?

**Comment by raboof** [comment]
* Created milestone 0.4.0
* Went back to recent PR's and attached 0.4.0 milestones
* Created 0.4.0 'release' in github linking to that milestone
* Created milestone 0.4.1

Not completely sure this is worth it, WDYT? If so we should document the process and make sure we always attach milestones to PR's/issues, and document this part of the release procedure.

**Comment by ignasi35** [comment]
> Not completely sure this is worth it, WDYT? If so we should document the process and make sure we always attach milestones to PR's/issues, and document this part of the release procedure.

+1

**Comment by dwijnand** [comment]
> Not completely sure this is worth it, WDYT? If so we should document the process and make sure we always attach milestones to PR's/issues, and document this part of the release procedure.

I don't feel strongly about the milestone maintenance nor about having very detailed release notes (i.e. linking to a milestone or even the last-tag-to-this-tag compare view is sufficient).  The one thing that I'd like is that releases created a GitHub release (I wasn't aware 0.4.0 was out).

**Comment by raboof** [comment]
> I wasn't aware 0.4.0 was out

Ah, GitHub produces notifications when a release is created in GitHub rather than 'just' a tag?

**Comment by dwijnand** [comment]
Correct.
