### ISSUE TITLE
Release for Scala 2.13.0-RC2

### ISSUE THREAD

**Issue by dwijnand** [lightbend/ssl-config#168]
See https://github.com/scala/make-release-notes/blob/2.13.x/projects-2.13.md for both the dependencies and also update it when this issue is resolved.

Depends on:

- [x] etorreborre/specs2#741 http://repo1.maven.org/maven2/org/specs2/specs2-matcher-extra_2.13.0-RC2/

**Comment by raboof** [comment]
I did a back-release of 0.4.0 for RC2, but this cannot be merged to master since we need specs2 for that.
