### ISSUE TITLE
"Secure by Default" SSLEngine

### ISSUE THREAD

**Issue by wsargent** [lightbend/ssl-config#17]
Recommend [RFC 7525](https://tools.ietf.org/html/rfc7525).  Most of this is server side, and we may want this to go into another library.

I poked at a "secure by default" SSLEngineFactory here:

https://github.com/wsargent/java-rfc7525/blob/master/src/main/java/com/example/RFC7525SSLEngineFactory.java

This was intended to be something like https://developer.android.com/reference/android/net/SSLCertificateSocketFactory.html (which actually sets hostname verification on by default!) but I got distracted. :-/

**Comment by ktoso** [comment]
Great pointer and point to start from, thanks!

**Comment by wsargent** [comment]
This is already addressed by recent versions of JSSE.
