### ISSUE TITLE
Using ssl-config with java.net.HttpURLConnection

### ISSUE THREAD

**Issue by PiotrJander** [lightbend/ssl-config#194]
With `ssl-config` I can add a self-signed certificate:

```hocon
ssl-config {
  trustManager = {
    stores = [
      { type = "PEM", path = <path> }
    ]
  }
}
```

Can I use such certificate with Java's `java.net.HttpURLConnection`? If so, can this be added to documentation?

**Comment by wsargent** [comment]
This isn't a bug.  

Technically what you want is an SSLContext with a trust manager which contains a trust store which contains that certificate.  Once you have that SSLContext, you can set it on HTTPURLConnection using `httpsCon.setSSLSocketFactory(sslContext.getSocketFactory());`

So yes, but also it's not anything to do with ssl-config itself.
