### ISSUE TITLE
Ciphers and algorithms should be defined in reference.conf

### ISSUE THREAD

**Issue by wsargent** [lightbend/ssl-config#23]
We shouldn't need hardcoded constant files all over the place:

https://github.com/typesafehub/ssl-config/blob/master/ssl-config-core/src/main/scala/com/typesafe/sslconfig/ssl/Ciphers.scala

**Comment by ktoso** [comment]
Yeah, another very good point, thanks.

**Comment by ktoso** [comment]
Let's ping tickets in case you're working on any of these (I'll do the same).

**Comment by wsargent** [comment]
Addressed through recent versions of JSSE.
