### ISSUE TITLE
TLS 1.3 support

### ISSUE THREAD

**Issue by pjfanning** [lightbend/ssl-config#236]
https://lightbend.github.io/ssl-config/Protocols.html does not specifically list TLS v1.3. I did try the `ssl-config.protocol = "TLSv1.3"` setting in my Play application.conf but it did not seem to have an affect.

Would it be possible to add v1.3 support and if it already exists, could you update the HTML page?

**Comment by wsargent** [comment]
I think it’s a straight pass through to the SSL context.  You may need to use a more recent version of java that supports TLS 1.3?

**Comment by pjfanning** [comment]
Thanks. I am using Java 11 but I think the real issue is that play-server is not picking up the param. I will try to debug more.
