### ISSUE TITLE
Release matching akka-2.6.x?

### ISSUE THREAD

**Issue by rovarga** [lightbend/ssl-config#246]
Would it be possible to issue a 0.4.2 release, to allow OSGi+Akka users to upgrade to akka-2.6.x? Lack of release containing https://github.com/lightbend/ssl-config/commit/71e217c867add2cf53d5e7b888e12469213d359a is currently holding up https://jira.opendaylight.org/browse/ODLPARENT-223 which we either resolve in next 8 weeks or kick down 6 months down the road.

**Comment by raboof** [comment]
Should be on its way to maven central now, thanks for the ping!
