### ISSUE TITLE
SSL Handshake failure due to NullPointerException in CompositeX509KeyManager

### ISSUE THREAD

**Issue by ramanalv** [lightbend/ssl-config#43]
SSLHandshake failing due to NullPointerException in logger.debug  calls in CompositeX509KeyManager#chooseEngineServerAlias and other similar calls. Upon further investigation,SSLHandshaker(http://code.metager.de/source/xref/openjdk/jdk8/jdk/src/share/classes/sun/security/ssl/ServerHandshaker.java#setupPrivateKeyAndChain) 
interestingly always sets the issuers null which is root cause for NullPointerException and 
as a result SSL-handshake fails bcz Certificate that binds to the Server will not be provided to the client as part of ServerHello

**Comment by ktoso** [comment]
Any more details or a reproducer?

**Comment by ramanalv** [comment]
Simple ssl-config with keyManager and trustManager to create SSLContext for binding a certificate to Server is good enough to reproduce this issue. Here are sample configuration and code snippets to reproduce this issue.

Sample Config:

`akka.ssl-config {
  protocol = "TLS"
  revocationLists = []
  enabledProtocols = ["TLSv1.2", "TLSv1.1"]
  enabledCipherSuites = [
    "TLS_DHE_RSA_WITH_AES_256_CBC_SHA",
    "TLS_DHE_RSA_WITH_AES_128_CBC_SHA",
    "TLS_DHE_DSS_WITH_AES_128_CBC_SHA",
    "TLS_RSA_WITH_AES_256_CBC_SHA",
    "TLS_RSA_WITH_AES_128_CBC_SHA",
    "TLS_EMPTY_RENEGOTIATION_INFO_SCSV"
  ]
  disabledSignatureAlgorithms = ["MD2", "MD4", "MD5"]
  disabledKeyAlgorithms = ["RSA keySize < 2048", "DSA keySize < 2048", "EC keySize < 224"""]
  //Make sure to set default to false to take effect the current configurations of trust managers.
  default = false
  trustManager = {
    stores = [
      { path: ${java.home}/lib/security/cacerts} # Fallback to default JSSE trust store
    ]
  }

  keyManager = {
    stores = [
      // Add Server key store here that contains server's private key.
      { type = "JKS", path: ${?TRUST_STORE}, password=${?TRUST_STORE_PASSWD}}
    ]
  }
}`

Use the following SSLContext to 


`case class CarbonSSLContextCreator(system: ActorSystem) extends HttpsContextCreator {

  def sslConfig: AkkaSSLConfig = AkkaSSLConfig(system)

  def https(): HttpsConnectionContext = {
    val config = sslConfig.config

    val log = Logging(system, getClass)
    val mkLogger = new AkkaLoggerFactory(system)

    // initial ssl context!
    val sslContext = if (sslConfig.config.default) {
      log.debug("buildSSLContext: ssl-config.default is true, using default SSLContext")
      sslConfig.validateDefaultTrustManager(config)
      SSLContext.getDefault
    } else {
      // break out the static methods as much as we can...
      val keyManagerFactory = sslConfig.buildKeyManagerFactory(config)
      val trustManagerFactory = sslConfig.buildTrustManagerFactory(config)
//      val sslContext = SSLContext.getInstance("TLS")
      new ConfigSSLContextBuilder(mkLogger, config, keyManagerFactory, trustManagerFactory).build()
    }
    val https = ConnectionContext.https(sslContext)
    https
  }
}`

`Http().bind(host, port,CarbonSSLContextCreator.https()).via(connectionFailureMonitor).to(Sink.foreach { connection =>
              //        Http().bind(host, port).via(connectionFailureMonitor).to(Sink.foreach { connection =>
              logger.debug(s"$this: accepted new connection from " + connection.remoteAddress)
              connection handleWithAsyncHandler route
            }).run()`

**Comment by ramanalv** [comment]
BTW, I already made a fix and let me know if you want I can submit a PR for this issue.

**Comment by wsargent** [comment]
@ktoso I think this is addressed by the PR that @note made https://github.com/typesafehub/ssl-config/pull/42/commits/c17d514dae23f8bdcdcbd85e676bcb2351f2de98#diff-f8fe48fe767e9f7262dd05d650304469R35

**Comment by ramanalv** [comment]
Thanks for your quick response and good to know that it is already addressed. BTW, is that change made into any release branch?

**Comment by ktoso** [comment]
As you can see on the linked PR it has not been merged yet, it will be soon though

**Comment by ktoso** [comment]
Thanks for spotting this Will
