### ISSUE TITLE
More flexible keystore handling

### ISSUE THREAD

**Issue by wsargent** [lightbend/ssl-config#44]
Currently, ssl-config is limited by the underlying API which does not allow for flexible keystore management.

There's a facility in JDK 1.8 that allows you to have keystore entries protected with different passwords!  

https://docs.oracle.com/javase/8/docs/technotes/guides/security/jsse/JSSERefGuide.html#MultiDynamicKeystores

> The java.security.KeyStore.Builder class abstracts the construction and initialization of a KeyStore object. It supports the use of CallbackHandler for password prompting, and its subclasses can be used to support additional features as desired by an application. For example, it is possible to implement a Builder that allows individual KeyStore entries to be protected with different passwords. The javax.net.ssl.KeyStoreBuilderParameters class then can be used to initialize a KeyManagerFactory using one or more of these Builder objects.

This is very exciting and should be investigated further.

**Comment by wsargent** [comment]
Also see https://bugs.openjdk.java.net/browse/JDK-4389689

**Comment by mgrandi** [comment]
Hello,

Is this the correct ticket to watch / reference when referring to the fact that ssl-config only allows you to specify 1 password (for the key store itself), and not passwords for individual keys within the key store?

I'm also confused because it seems that the stuff you reference was seemingly available in java 6, so i'm a bit puzzled on why support for this wasn't built into ssl-config to begin with, but we can get by with just having the keys have the same password as the keystore itself

**Comment by wsargent** [comment]
There was a lot of breakage in 1.6 -- see https://github.com/akka/akka/issues/20381#issuecomment-227843372

**Comment by wsargent** [comment]
Some example code:

```java
    KeyStore.Builder keystore(String type, String filename, String password) {
        return KeyStore.Builder.newInstance("JKS", null, new File(filename), new KeyStore.PasswordProtection(password.toCharArray()));
    }

    public KeyManagerFactory createKeyManagerFactory(KeyStore.Builder... keystores) throws NoSuchAlgorithmException, InvalidAlgorithmParameterException {
        ManagerFactoryParameters ksParams = new KeyStoreBuilderParameters(Arrays.asList(keystores));
        KeyManagerFactory factory = KeyManagerFactory.getInstance("NewSunX509");
        factory.init(ksParams);
        return factory;
    }

    SSLSocketFactory createSocketFactory(KeyManagerFactory kmf, TrustManagerFactory tmf) throws Exception {
        SSLParameters sslParams = new SSLParameters();
        sslParams.setEndpointIdentificationAlgorithm("HTTPS");
        SSLContext ctx = SSLContext.getInstance("TLSv1.2");

        ctx.init(kmf.getKeyManagers(), null, null);
        SSLSocketFactory ssf = ctx.getSocketFactory();
        return ssf;
    }
```

**Comment by wsargent** [comment]
Also see a dynamic filewatch cert being used by https://github.com/cloudfoundry/java-buildpack-security-provider

**Comment by mgrandi** [comment]
Why was this closed? Was it implemented?

**Comment by wsargent** [comment]
It's closed because flexible keystore handling is _complicated_ and the password management feature of keystores is not fully implemented in JSSE regardless:

> What it means by "keys within one KeyStore protected by different keys"… it means "protected by different passwords", but that isn't the case: if you use the KeyStore.Builder API with a PKCS12 file, you're still matching a keystore with a PasswordProtection, and there is no way to match a password to a specific alias. If the keystore and all private key entries in the keystore have the same password, then everything works fine, but you still can't differentiate inside of a keystore.

https://tersesystems.com/blog/2018/09/08/keymanagers-and-keystores/

Likewise, dynamic handling of keystores and reloading is also surprisingly complex, even given the `Keystore.Builder` API:

> You may note that the private key password is not shown as an option. That's because prior to 1.6, the key's password had to be the same as the key store's password, and the default on keytool is still to use the store password as the key password if it not specified. There's a number of ancient bugs attached to password protected keystores, but I won't bore you with the details. Just don't get fooled into thinking that passwords on keystores mean anything, or provide you with any security.
> It is technically possible as of 1.8 to use a java.security.KeyStore.Builder, and the JSSE documentation is very keen to point out that "For example, it is possible to implement a Builder that allows individual KeyStore entries to be protected with different passwords. The javax.net.ssl.KeyStoreBuilderParameters class then can be used to initialize a KeyManagerFactory using one or more of these Builder objects." But you're still writing code to do it – it's not an option from the system properties.
> If you want to aggregate keystores (as opposed to importing certificates a la cacerts above), then your options are limited. You can't specify multiple keystores as system properties, and both KeyManager and TrustManager will only work with a single keystore.

https://tersesystems.com/blog/2018/07/28/building-java-keystores/
