### ISSUE TITLE
publish for Scala 2.13.0-M3, please

### ISSUE THREAD

**Issue by SethTisue** [lightbend/ssl-config#73]
Specs2 4.0.x has now been published for M3. I think that was the major missing dependency

ssl-config is already building, and tests passing, in the 2.13 community build, so that's a good sign that this probably won't be hard

**Comment by ktoso** [comment]
Seems there is no java8-compat for M3?
 http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22scala-java8-compat_2.13.0-M3%22

**Comment by SethTisue** [comment]
yeah. I'll publish genjavadoc and scala-java8-compat soon (within next day or so)

**Comment by ktoso** [comment]
Figured that we don't need ssl-config-akka which breaks the cyclic dependency, so I now released: 0.2.2 for Scala 2.13.0-M3
