### ISSUE TITLE
Need Automatic-Module-name

### ISSUE THREAD

**Issue by xuning97** [lightbend/ssl-config#77]

**Comment by wsargent** [comment]
Can you provide more details?

**Comment by ktoso** [comment]
While ticket is pretty non-descriptive... I know what it's about; we should add such things: 
- https://github.com/akka/akka/blob/master/project/AutomaticModuleName.scala 
- and use: https://github.com/akka/akka/blob/master/build.sbt#L59

such that it can be used as "module" under JDK9, even without being a real module.

Would you submit a PR, the attached code snippets should be easily to copy and apply to this build from Akka; @xuning97

**Comment by xuning97** [comment]
sure

**Comment by xuning97** [comment]
Submitted a PR #78

**Comment by ktoso** [comment]
FYI this was released now as 0.2.3 :shipit:
