### ISSUE TITLE
Support Java 11

### ISSUE THREAD

**Issue by wsargent** [lightbend/ssl-config#98]
Should see how to work the `Unsafe` shenanigans into JDK 1.9 safely, and establish migration path.

 https://github.com/scala/scala-dev/issues/139

**Comment by xuwei-k** [comment]
compile error with JDK11


https://github.com/lightbend/ssl-config/blob/d695f63fae714a7fe7c0ff6dbd3423287c4c3303/ssl-config-core/src/main/scala/com/typesafe/sslconfig/ssl/DefaultHostnameVerifier.scala#L40

```
Welcome to Scala 2.12.7 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_181).
Type in expressions for evaluation. Or try :help.

scala> sun.security.util.HostnameChecker.`match` _
res0: (String, java.security.Principal) => Boolean = $$Lambda$1047/225753796@5ff90645
```

```
Welcome to Scala 2.12.7 (Java HotSpot(TM) 64-Bit Server VM, Java 11).
Type in expressions for evaluation. Or try :help.

scala> sun.security.util.HostnameChecker.`match` _
<console>:12: error: value match is not a member of object sun.security.util.HostnameChecker
       sun.security.util.HostnameChecker.`match` _
                                         ^
```

**Comment by dwijnand** [comment]
It takes an extra param now: https://github.com/dmlloyd/openjdk/commit/8ffa37ccd02429d79096d59be1efb79a2a956654#diff-d3a012ee503c50b9937d3bc83411d719L87 ..

**Comment by dwijnand** [comment]
Wait, but it's overloaded.. https://github.com/dmlloyd/openjdk/commit/8ffa37ccd02429d79096d59be1efb79a2a956654#diff-d3a012ee503c50b9937d3bc83411d719R103

**Comment by SethTisue** [comment]
see #100

**Comment by SethTisue** [comment]
@dwijnand @ignasi35 this is now the top blocker (blocking the most downstream projects) in the Scala community build on JDK 11

**Comment by dwijnand** [comment]
OK, I'll negotiate for it to be part of the next sprint.

**Comment by xuwei-k** [comment]
https://hg.openjdk.java.net/jdk/jdk11/rev/68fa3d4026ea#l165.29

The `match` method removed due to TLS 1.3 support.
